version: "3"
services:
  redis:
    image: redis:alpine3.20
    restart: always
    volumes:
      - ./data/redis:/data
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - db-network
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    ports:
      - 8081:8081
    environment:
      - REDIS_HOSTS=local:redis:6379
    networks:
      - db-network

networks:
  db-network:
    driver: bridge

import 'redis/dist/index'
